spring:
  application:
    name: heartsync-server
  config:
    activate:
      on-profile: default, local, dev

  datasource:
    url:
    username: user
    password: pw
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  application:
    name: heartsync-server
  config:
    activate:
      on-profile: prod

  datasource:
    url:
    username: user
    password: pw
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: localhost
      port: 6379